<<<<<<< HEAD
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-9(1zrxvdc^yw*wr!&@fh6o*g!3qwtr*xdm+21w&g2hyh(g)9+9'

=======
"""
Django settings for korochki project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9(1zrxvdc^yw*wr!&@fh6o*g!3qwtr*xdm+21w&g2hyh(g)9+9'

# SECURITY WARNING: don't run with debug turned on in production!
>>>>>>> 3dc41b8156e7404e074383ad3ee1b8df3b6dc39f
DEBUG = True

ALLOWED_HOSTS = []

<<<<<<< HEAD
=======

# Application definition

>>>>>>> 3dc41b8156e7404e074383ad3ee1b8df3b6dc39f
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
<<<<<<< HEAD
    'apps.users',
    'apps.applications',
=======
    'apps.users',              
    'apps.applications',        
>>>>>>> 3dc41b8156e7404e074383ad3ee1b8df3b6dc39f
    'apps.core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'korochki.urls'
<<<<<<< HEAD

AUTH_USER_MODEL = 'users.User'
=======
AUTH_USER_MODEL = 'users.CustomUser'
>>>>>>> 3dc41b8156e7404e074383ad3ee1b8df3b6dc39f

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
<<<<<<< HEAD
        'DIRS': [BASE_DIR / 'templates'],
=======
        'DIRS': [BASE_DIR / 'templates'], #если что, стандартно, скобки пустые, то что я указал это глобальная папка с шаблонами, стоит запомнить
>>>>>>> 3dc41b8156e7404e074383ad3ee1b8df3b6dc39f
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'korochki.wsgi.application'

<<<<<<< HEAD
=======

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

>>>>>>> 3dc41b8156e7404e074383ad3ee1b8df3b6dc39f
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

<<<<<<< HEAD
AUTH_PASSWORD_VALIDATORS = []

LANGUAGE_CODE = 'ru-ru'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

=======

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

>>>>>>> 3dc41b8156e7404e074383ad3ee1b8df3b6dc39f
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

LOGIN_URL = '/users/login/'
<<<<<<< HEAD
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/users/login/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
=======
LOGIN_REDIRECT_URL = '/' 
LOGOUT_REDIRECT_URL = '/users/login/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
>>>>>>> 3dc41b8156e7404e074383ad3ee1b8df3b6dc39f
